language: php

compiler:
  - gcc
  - clang

os:
  - linux

matrix:
  include:
    - php: 7.0
      env: USE_VALGRIND=1
    - php: 7.1
      env: USE_VALGRIND=1
    - php: 7.2
      env: USE_VALGRIND=1
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly

addons:
  apt:
    packages: valgrind

notifications:
  email: dev@service.viest.me

before_script:
  - sudo apt-get install -y wget
  - wget https://www.foundationdb.org/downloads/5.1.7/ubuntu/installers/foundationdb-clients_5.1.7-1_amd64.deb
  - wget https://www.foundationdb.org/downloads/5.1.7/ubuntu/installers/foundationdb-server_5.1.7-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_5.1.7-1_amd64.deb foundationdb-server_5.1.7-1_amd64.deb
  - sudo service foundationdb start
  - phpize && ./configure && make clean && make

branches:
  only:
    - master
    - develop

script:
    - ./travis/run-test.sh
    - make clean && phpize --clean
    - phpize && ./configure --enable-reader && make clean && make
    - if [ -n "$USE_VALGRIND" ]; then REPORT_EXIT_STATUS=1 php -n run-tests.php -m -n -d extension_dir=./modules/ -d extension=xlswriter.so -P --show-diff --set-timeout 120; fi